// File generated by scripts/pre-build.js

export const commit = "063de3055ceb3d01393168e89cb9023f838fcc6d";
export const commitShort = "063de30";
export const commitAuthor = "Fabian Cook";
export const commitEmail = "hello@fabiancook.dev";
export const commitMessage = "Get product image by index, #78";
export const commitAt = "2023-06-09T10:39:57.000Z";
export const secondsBetweenCommitAndBuild = 1456.14;
export const minutesBetweenCommitAndBuild = 24.27;
export const timeBetweenCommitAndBuild = "24 minutes and 16 seconds";
// Variables to be replaced after tests
export const secondsBetweenCommitAndTestCompletion = "";
export const minutesBetweenCommitAndTestCompletion = "";
export const timeBetweenCommitAndTestCompletion = "";